### ISSUE TITLE
Bookmarklet：请求增加书签还原普通js代码

### ISSUE THREAD

**Issue by fucker300** [jerrylususu/mainonly#10]
大佬好，Bookmarklet Maker使用很方便，拿来做了一个针对性获取网站localStorage的书签，但是想要更新代码发现需要重新写书签原始内容，请求增加书签还原普通js代码的功能，方便清空缓存后还能快速测试更新书签代码。

**Comment by jerrylususu** [comment]
抱歉没有太理解你的问题。
- 如果你指的是本项目的代码，可以参考 https://github.com/jerrylususu/mainonly/blob/main/mainonly.js
- 如果你使用maker制作小书签，你自己应该是拥有原始代码的，maker生成的代码经过了最小化，变量名和注释都会被修改。
- 如果你想从已有的小书签代码，格式化为带有缩进比较好读的代码，可以用 js beautifier （例如[这个](https://beautifier.io)）。
- 如果你只是想要快速验证代码功能，可以考虑将原始代码直接在浏览器的开发者工具控制台执行，效果和点击小书签是一样的。

**Comment by fucker300** [comment]
> 抱歉没有太理解你的问题。
> 
> * 如果你指的是本项目的代码，可以参考 https://github.com/jerrylususu/mainonly/blob/main/mainonly.js
> * 如果你使用maker制作小书签，你自己应该是拥有原始代码的，maker生成的代码经过了最小化，变量名和注释都会被修改。
> * 如果你想从已有的小书签代码，格式化为带有缩进比较好读的代码，可以用 js beautifier （例如[这个](https://beautifier.io)）。
> * 如果你只是想要快速验证代码功能，可以考虑将原始代码直接在浏览器的开发者工具控制台执行，效果和点击小书签是一样的。

感谢大佬回复，我是使用maker制作小书签，maker生成的代码并不可逆，自己写的书签如果要后续更新的话最好还是自己备份一下原始代码。
