### ISSUE TITLE
能不能设置按Esc显示隐藏的元素后回到之前的位置？

### ISSUE THREAD

**Issue by Gally-Youko** [jerrylususu/mainonly#3]
比如说我之前在网页中浏览到了中下部分，然后用mainonly后退出，就会回到网页的最上面。如果能从原来的位置继续就方便了。

**Comment by Gally-Youko** [comment]
我刚做出来发布了：
https://github.com/Gally-Youko/mainonlyRevert

**Comment by jerrylususu** [comment]
这个功能看起来很有用，考虑提个 Pull Request？

**Comment by jerrylususu** [comment]
主干代码已更新，增加了两处修改：
1. 用 `visibility: hidden` 取代 `display:none`，前者可以在不展示元素的同时保持页面布局
2. 撤销隐藏前记录 scrollY 坐标，操作完成后滚回对应坐标
