### ISSUE TITLE
页面显示问题

### ISSUE THREAD

**Issue by xianyuSR** [jerrylususu/mainonly#6]
还是这个网页[https://www.sciencedirect.com/journal/cement-and-concrete-composites/publish/guide-for-authors](url)，如果只选中某一个单独的段落，实际上会显示这个段落附近的好多段落，如下图所示~
![image](https://github.com/jerrylususu/mainonly/assets/50240134/bc50c150-b9b4-44aa-ac3a-d80210086d8a)

**Comment by Gally-Youko** [comment]
[Code Behavior and Issues.md](https://github.com/jerrylususu/mainonly/files/13784395/Code.Behavior.and.Issues.md)
这和我这个问题是一样的

**Comment by xianyuSR** [comment]
> [Code Behavior and Issues.md](https://github.com/jerrylususu/mainonly/files/13784395/Code.Behavior.and.Issues.md) 这和我这个问题是一样的

把书签更新成了md文件里最后那一行压缩代码，还是会出现类似的问题，而且启用书签后选择文本时滚轮滚动会出现很多红框

**Comment by Gally-Youko** [comment]
> > [Code Behavior and Issues.md](https://github.com/jerrylususu/mainonly/files/13784395/Code.Behavior.and.Issues.md) 这和我这个问题是一样的
> 
> 把书签更新成了md文件里最后那一行压缩代码，还是会出现类似的问题，而且启用书签后选择文本时滚轮滚动会出现很多红框

这个是失败的，我那天尝试了很久没搞出来就不搞了

**Comment by xianyuSR** [comment]
> > > [Code Behavior and Issues.md](https://github.com/jerrylususu/mainonly/files/13784395/Code.Behavior.and.Issues.md) 这和我这个问题是一样的
> > 
> > 
> > 把书签更新成了md文件里最后那一行压缩代码，还是会出现类似的问题，而且启用书签后选择文本时滚轮滚动会出现很多红框
> 
> 这个是失败的，我那天尝试了很久没搞出来就不搞了

哦哦，怪不得，期待大佬们的更新吧

**Comment by jerrylususu** [comment]
基于 https://github.com/jerrylususu/mainonly/pull/7 更新了一个版本，修改了元素选择器（从基于 class 改成了基于 id），纯文本节点也可以正常隐藏了，可以再试试是否解决了问题。

![image](https://github.com/jerrylususu/mainonly/assets/17522475/a5e0c69a-4875-4511-bba0-332283a61f89)

**Comment by xianyuSR** [comment]
> 基于 #7 更新了一个版本，修改了元素选择器（从基于 class 改成了基于 id），纯文本节点也可以正常隐藏了，可以再试试是否解决了问题。
> 
> ![image](https://private-user-images.githubusercontent.com/17522475/293226479-a5e0c69a-4875-4511-bba0-332283a61f89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MTE4MDAsIm5iZiI6MTcwMzgxMTUwMCwicGF0aCI6Ii8xNzUyMjQ3NS8yOTMyMjY0NzktYTVlMGM2OWEtNDg3NS00NTExLWJiYTAtMzMyMjgzYTYxZjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDAwNTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MWU5NDBiZmI4NTE2ZGQ4YTYzYzQ3ODc0YjYwNDA0NTUzMjkxMjU5MjM3MWRiMjVjZDcxOGRhMzU1ODQ0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mod3No2jdp4vM9dTgFUCjsyoJwmIAbuCpLnHF1Y3er0)

大佬，大部分段落都正常了，对于比较长的段落，我发现使用小书签后无法选择元素~
![image](https://github.com/jerrylususu/mainonly/assets/50240134/39e85882-2ffa-4953-8e22-8856d13ba2dc)

**Comment by posthumz** [comment]
> 大佬，大部分段落都正常了，对于比较长的段落，我发现使用小书签后无法选择元素~

这个的确做不到，因为这个段落是[文本节点](https://developer.mozilla.org/en-US/docs/Web/API/Text)不是[HTML元素](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLElement)，不能应用样式。
反而是段中斜体的`<i>without</i>`可以选中
![图片](https://github.com/jerrylususu/mainonly/assets/63167402/e3bbd929-9711-4d01-960e-c42c82572f9a)

（一般来说正确的做法是每个段落都用`<p></p>`包起来，像这个网页没这样做那确实没办法

**Comment by xianyuSR** [comment]
> > 大佬，大部分段落都正常了，对于比较长的段落，我发现使用小书签后无法选择元素~
> 
> 这个的确做不到，因为这个段落是[文本节点](https://developer.mozilla.org/en-US/docs/Web/API/Text)不是[HTML元素](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLElement)，不能应用样式。 反而是段中斜体的`<i>without</i>`可以选中 ![图片](https://private-user-images.githubusercontent.com/63167402/293328703-e3bbd929-9711-4d01-960e-c42c82572f9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4Mzc1ODksIm5iZiI6MTcwMzgzNzI4OSwicGF0aCI6Ii82MzE2NzQwMi8yOTMzMjg3MDMtZTNiYmQ5MjktOTcxMS00ZDAxLTk2MGUtYzQyYzgyNTcyZjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA4MDgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMGNlY2I0OTVlOWM4NzY5NWY1MTViYzVkNzEyMGJiOGJmMjFjYTBjNzgyNzU4MTE0NzVlNDBjMTg4MDM0ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VKndLseBJa3qqc62axFK102f6AxkkGB21u4-N5cex-g)
> 
> （一般来说正确的做法是每个段落都用`<p></p>`包起来，像这个网页没这样做那确实没办法

懂了，感谢！！
